#!/usr/bin/env bash

dart pub global activate full_coverage

set -e

# Function to test a module
test_module() {
  local module_dir="$1"
  echo ""
  echo "##################################################################"
  echo "Testing project $module_dir"
  echo "##################################################################"
  (cd "$module_dir" && flutter test) # Change directory and run tests
  if [ $? -ne 0 ]; then
    echo "Tests failed in $module_dir"
    exit 1
  fi
}

## Test all infrastructure
for directory in $(find infrastructure -type f -iname pubspec.yaml | awk -F pubspec.yaml '{ print $1 }' | sort); do
  echo ""
  echo "##################################################################"
  echo "Testing project $directory"
  echo "##################################################################"
  scripts/test-module test $directory
done

## Test all features
for directory in $(find features -type f -iname pubspec.yaml | awk -F pubspec.yaml '{ print $1 }' | sort); do
  echo ""
  echo "##################################################################"
  echo "Testing project $directory"
  echo "##################################################################"
  scripts/test-module test $directory
done

echo "All tests completed successfully."