name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Test Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'

      - name: Install dependencies
        run: flutter pub get
        working-directory: app

      - name: Run Flutter tests
        run: flutter test
        working-directory: app

      - name: Build APK
        run: flutter build apk --release
        working-directory: app

      - name: Build AppBundle
        run: flutter build appbundle
        working-directory: app

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab
